development:
  server: "http://pure-leaf-8518.herokuapp.com/faye"
  secret_token: "buka"
test:
  sserver: "http://pure-leaf-8518.herokuapp.com/faye"
  secret_token: "buka"
production:
  sserver: "http://pure-leaf-8518.herokuapp.com/faye"
  secret_token: "buka"
  signature_expiration: 3600 # one hour
